#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed
# This script should be idempotent.

set -ux

DEFAULT_REPLSET_NAME=`config-get replicaset`
REPLICASET_MASTER=`config-get replicaset_master`
HOSTNAME=`unit-get public-address`

############################################################################################################
# Are we connecting to an existing replica set?
############################################################################################################
if [ "${REPLICASET_MASTER}" != "auto" ]; then
        grep "${DEFAULT_REPLSET_NAME}" /etc/init/mongodb.conf
        if [ $? -ne 0 ];then
                sed -i -e "s/ -- / -- --replSet ${DEFAULT_REPLSET_NAME} /" /etc/init/mongodb.conf
                service mongodb stop
                rm -f /var/lib/mongodb/mongod.lock
                service mongodb start
        fi
        mongo --host ${REPLICASET_MASTER} --eval "rs.add(\""${HOSTNAME}"\")"
fi

