#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed
# This script should be idempotent.

set -ux

relation-set hostname=`hostname -f` replset=`facter replset-name`

echo $ENSEMBLE_REMOTE_UNIT joined
