#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed
# This script should be idempotent.

set -ux

HOSTNAME=`unit-get public-address`
REPLICASET=`config-get replicaset`

relation-set hostname=${HOSTNAME} replset=${REPLICASET}

echo $JUJU_REMOTE_UNIT joined
