#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot

set -ux

############################################################################################################
# Set some variables that we'll need for later
############################################################################################################
DEFAULT_REPLSET_NAME=`config-get replicaset`
#HOSTNAME=`hostname -f`
HOSTNAME=`unit-get public-address`
EPOCH=`date +%s`
INSTALL_ORDER=$(echo ${JUJU_UNIT_NAME} | awk -F/ '{ print $2 }')
WEB_ADMIN_UI=`config-get web_admin_ui`
REPLICASET_MASTER=`config-get replicaset_master`
DEFAULT_PORT=`config-get default_port`


############################################################################################################
# Install mongodb
############################################################################################################
DEBIAN_FRONTEND=noninteractive apt-get install -y mongodb


############################################################################################################
# Change the default mongodb configuration
############################################################################################################
sed -e "s/#master = true/master = true/" \
    -e "s/bind_ip/#bind_ip/" \
    -e "s/#port = 27017/port = ${DEFAULT_PORT}/" \
    -i /etc/mongodb.conf


############################################################################################################
# Reconfigure the upstart script to include the replica-set option.
# We'll need this so, when we add nodes, they can all talk to each other.
# Replica sets can only talk to each other if they all belong to the same
# set.  In our case, we have defaulted to "myset".
############################################################################################################
# Web Admin UI
if [ "$WEB_ADMIN_UI" == "yes" ]; then
	sed -i -e "s/ -- / -- --rest /" /etc/init/mongodb.conf
fi

if [ "${REPLICASET_MASTER}" != "auto" ]; then
	sed -i -e "s/ -- / -- --replSet ${DEFAULT_REPLSET_NAME} /" /etc/init/mongodb.conf
fi


############################################################################################################
# stop then start ( *** not restart **** )  mongodb so we can finish the configuration
############################################################################################################
service mongodb stop
# There is a bug in the upstart script that leaves a lock file orphaned.... Let's wipe that file out
rm -f /var/lib/mongodb/mongod.lock
service mongodb start


############################################################################################################
# Are we connecting to an existing replica set?
############################################################################################################
if [ "${REPLICASET_MASTER}" != "auto" ]; then
	grep "${DEFAULT_REPLSET_NAME}" /etc/init/mongodb.conf
	if [ $? -ne 0 ];then
        	sed -i -e "s/ -- / -- --replSet ${DEFAULT_REPLSET_NAME} /" /etc/init/mongodb.conf
        	service mongodb stop
        	rm -f /var/lib/mongodb/mongod.lock
        	service mongodb start
	fi
	mongo --host ${REPLICASET_MASTER} --eval "rs.add(\""${HOSTNAME}"\")"
fi


############################################################################################################
# Register the port
############################################################################################################
[ -x /usr/bin/open-port ] && open-port ${DEFAULT_PORT}/TCP
if [ "$WEB_ADMIN_UI" == "yes" ]; then
    [ -x /usr/bin/open-port ] && open-port $((${DEFAULT_PORT} + 1000))/TCP
fi

exit 0
