#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot

set -ux

############################################################################################################
# Install some utility packages needed for installation
############################################################################################################
DEBIAN_FRONTEND=noninteractive apt-get -y install facter facter-customfacts-plugin

############################################################################################################
# Set some variables that we'll need for later
############################################################################################################
DEFAULT_REPLSET_NAME=`config-get replicaset`
HOSTNAME=`hostname -f`
EPOCH=`date +%s`
fact-add install-time ${EPOCH}
WEB_ADMIN_UI=`config-get web_admin_ui`


############################################################################################################
# Install mongodb
############################################################################################################
DEBIAN_FRONTEND=noninteractive apt-get install -y mongodb


############################################################################################################
# Change the default mongodb configuration to bind to relfect that we are a master
############################################################################################################
sed -e "s/#master = true/master = true/" -e "s/bind_ip/#bind_ip/" -i /etc/mongodb.conf


############################################################################################################
# Reconfigure the upstart script to include the replica-set option.
# We'll need this so, when we add nodes, they can all talk to each other.
# Replica sets can only talk to each other if they all belong to the same
# set.  In our case, we have defaulted to "myset".
############################################################################################################
# Web Admin UI
if [ "$WEB_ADMIN_UI" == "True" ]; then
	sed -i -e "s/ -- / -- --rest /" /etc/init/mongodb.conf
fi
#if [ "$REPLSET_UI" == "True" ]; then
#	sed -i -e "s/ -- / -- --rest --replSet ${DEFAULT_REPLSET_NAME} /" /etc/init/mongodb.conf
#else
#	sed -i -e "s/ -- / -- --replSet ${DEFAULT_REPLSET_NAME} /" /etc/init/mongodb.conf
#fi


############################################################################################################
# stop then start ( *** not restart **** )  mongodb so we can finish the configuration
############################################################################################################
service mongodb stop
# There is a bug in the upstart script that leaves a lock file orphaned.... Let's wipe that file out
rm -f /var/lib/mongodb/mongod.lock
service mongodb start


############################################################################################################
# Initialize the replicaset
############################################################################################################
#sleep 5
#mongo --eval "rs.initiate()"
#sleep 5


############################################################################################################
# Register the port
############################################################################################################
[ -x /usr/bin/open-port ] && open-port 27017/TCP
if [ "$WEB_ADMIN_UI" == "True" ]; then
	[ -x /usr/bin/open-port ] && open-port 28017/TCP
fi
