#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.

############################################################################################################
# Set debugging information
############################################################################################################
set -ux

############################################################################################################
# Set some global variables
############################################################################################################
MY_HOSTNAME=`unit-get public-address`
MY_REPLSET=`config-get replicaset`
MY_INSTALL_ORDER=$(echo ${JUJU_UNIT_NAME} | awk -F/ '{ print $2 }')
MY_REPLICASET_MASTER=`config-get replicaset_master`


############################################################################################################
# If we are joining an existing replicaset cluster, just join and leave.
############################################################################################################
if [ "${MY_REPLICASET_MASTER}" != "auto" ]; then
	mongo --host ${MY_REPLICASET_MASTER} --eval "rs.add(\""${MY_HOSTNAME}"\")"
	exit $?
fi

MASTER_HOSTNAME=${MY_HOSTNAME}
MASTER_REPLSET=${MY_REPLSET}
MASTER_INSTALL_ORDER=${MY_INSTALL_ORDER}

echo "My hosntmae: ${MY_HOSTNAME}"
echo "My ReplSet: ${MY_REPLSET}"
echo "My install order: ${MY_INSTALL_ORDER}"

############################################################################################################
# Here we need to find out which is the first node ( we record the install order ).
# The one with the lowest order time is the master.
# Initialize the master node.
# Add the other nodes to the master's replica set.
############################################################################################################
# Find the master ( lowest install order )
for MEMBER in `relation-list`
do
   HOSTNAME=`relation-get hostname ${MEMBER}`
   REPLSET=`relation-get replset ${MEMBER}`
   INSTALL_ORDER=`relation-get install-order ${MEMBER}`
   if [ ${INSTALL_ORDER} -lt ${MASTER_INSTALL_ORDER} ];then
      MASTER_HOSTNAME=${HOSTNAME}
      MASTER_REPLSET=${REPLSET}
      MASTER_INSTALL_ORDER=${INSTALL_ORDER}
   fi
done

echo "Master Hostname: ${MASTER_HOSTNAME}"
echo "Master ReplSet: ${MASTER_REPLSET}"
echo "Master install order: ${MASTER_INSTALL_ORDER}"

# We should now have all the information about the master node.
# If the node has already been initialized, it will just inform you
# about it with no other consequence.
if [ "${MASTER_HOSTNAME}" == "${MY_HOSTNAME}" ]; then
   mongo --eval "rs.initiate()"
else
   mongo --host ${MASTER_HOSTNAME} --eval "rs.initiate()"
fi

# Now we need to add the rest of nodes to the replica set
for MEMBER in `relation-list`
do
   HOSTNAME=`relation-get hostname ${MEMBER}`
   REPLSET=`relation-get replset ${MEMBER}`
   INSTALL_ORDER=`relation-get install-order ${MEMBER}`
   if [ "${MASTER_HOSTNAME}" != "${HOSTNAME}" ]; then
      if [ "${HOSTNAME}" == "${MY_HOSTNAME}" ]; then
         mongo --eval "rs.add(\""${HOSTNAME}"\")"
      else
         mongo --host ${MASTER_HOSTNAME} --eval "rs.add(\""${HOSTNAME}"\")"
      fi
   fi
done

# Add myself to the replicaset if needed
if [ "${MASTER_HOSTNAME}" != "${MY_HOSTNAME}" ]; then
        mongo --host ${MASTER_HOSTNAME} --eval "rs.add(\""${MY_HOSTNAME}"\")"
fi


echo $JUJU_REMOTE_UNIT modified its settings
echo Relation settings:
relation-get
echo Relation members:
relation-list
