#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.

############################################################################################################
# Set debugging information
############################################################################################################
set -ux

############################################################################################################
# Set some global variables
############################################################################################################
MY_HOSTNAME=`hostname -f`
MY_REPLSET=`config-get replicaset`
MY_INSTALL_TIME=`facter install-time`
MY_REPLICASET_MASTER=`config-get replicaset_master`


############################################################################################################
# If we are joining an existing replicaset cluster, just join and leave.
############################################################################################################
if [ "${MY_REPLICASET_MASTER}" != "auto" ]; then
	mongo --host ${MY_REPLICASET_MASTER} --eval "rs.add(\""${MY_HOSTNAME}"\")"
	exit $?
fi

MASTER_HOSTNAME=${MY_HOSTNAME}
MASTER_REPLSET=${MY_REPLSET}
MASTER_INSTALL_TIME=${MY_INSTALL_TIME}

echo "My hosntmae: ${MY_HOSTNAME}"
echo "My ReplSet: ${MY_REPLSET}"
echo "My install time: ${MY_INSTALL_TIME}"

############################################################################################################
# Here we need to find out which is the first node ( we record the install time ).
# The one with the lowest install time is the master.
# Initialize the master node.
# Add the other nodes to the master's replica set.
############################################################################################################
# Find the master ( lowest install time )
for MEMBER in `relation-list`
do
   HOSTNAME=`relation-get hostname ${MEMBER}`
   REPLSET=`relation-get replset ${MEMBER}`
   INSTALL_TIME=`relation-get install-time ${MEMBER}`
   if [ ${INSTALL_TIME} -lt ${MASTER_INSTALL_TIME} ];then
      MASTER_HOSTNAME=${HOSTNAME}
      MASTER_REPLSET=${REPLSET}
      MASTER_INSTALL_TIME=${INSTALL_TIME}
   fi
done

echo "Master host: ${MASTER_HOSTNAME}"

# We should now have the lowest member of this relationship.  Let's get all of the information about it.
#for MEMBER in `relation-list`
#do
#   HOSTNAME=`relation-get hostname ${MEMBER}`
#   REPLSET=`relation-get replset ${MEMBER}`
#   INSTALL_TIME=`relation-get install-time ${MEMBER}`
#   if [ ${INSTALL_TIME} -eq ${MASTER_INSTALL_TIME} ]; then
#      MASTER_HOSTNAME=${HOSTNAME}
#      MASTER_REPLSET=${REPLSET}
#   fi
#done

echo "Master Hostname: ${MASTER_HOSTNAME}"
echo "Master ReplSet: ${MASTER_REPLSET}"
echo "Master install time: ${MASTER_INSTALL_TIME}"

# We should now have all the information about the master node.
# If the node has already been initialized, it will just inform you
# about it with no other consequence.
if [ "${MASTER_HOSTNAME}" == "${MY_HOSTNAME}" ]; then
   mongo --eval "rs.initiate()"
else
   mongo --host ${MASTER_HOSTNAME} --eval "rs.initiate()"
fi

# Now we need to add the rest of nodes to the replica set
for MEMBER in `relation-list`
do
   HOSTNAME=`relation-get hostname ${MEMBER}`
   REPLSET=`relation-get replset ${MEMBER}`
   INSTALL_TIME=`relation-get install-time ${MEMBER}`
   if [ "${MASTER_HOSTNAME}" != "${HOSTNAME}" ]; then
      if [ "${HOSTNAME}" == "${MY_HOSTNAME}" ]; then
         mongo --eval "rs.add(\""${HOSTNAME}"\")"
      else
         mongo --host ${MASTER_HOSTNAME} --eval "rs.add(\""${HOSTNAME}"\")"
      fi
   fi
done

# Add myself to the replicaset if needed
if [ "${MASTER_HOSTNAME}" != "${MY_HOSTNAME}" ]; then
        mongo --host ${MASTER_HOSTNAME} --eval "rs.add(\""${MY_HOSTNAME}"\")"
fi


echo $JUJU_REMOTE_UNIT modified its settings
echo Relation settings:
relation-get
echo Relation members:
relation-list
